### ISSUE TITLE
Downloads only checkout gives "shippingAddress name is invalid."

### ISSUE THREAD

**Issue by FZenM** [unzerdev/woocommerce#5]
When the checkout only has downloadable products, then it only has a billing address.

It is not possible to pass validation since it throws "shippingAddress name is invalid."

Different Payment Plugin does not trigger it. Payout is successfull. Eg. the one from CustomWeb or Paypal direct.

 I am trying to pin point it down some more in the code.

**Comment by fiedomedia** [comment]
Are there any updates to this issue? 
Still not working...

**Comment by FZenM** [comment]
but it is not the only problem I have with the new plugins

**Comment by ebravo25** [comment]
any updates?

**Comment by FZenM** [comment]
I fixed it back then, but ran into another problem in the payment processing. The latest release has the issue in the fix log, but I have not had a chance to validate it yet.

**Comment by FZenM** [comment]
Seems to work now, but another issue. Will send PM with a debug_log extract of a failed transaction.
